allowed-idents-below-min-chars = ["..", "f"]
check-private-items = true
cognitive-complexity-threshold = 80
missing-docs-allow-unused = true
module-items-ordered-within-groupings = ["modules", "use"]
source-item-ordering = ["module", "trait"]
struct-field-name-threshold = 1
