services:
    postgresdb:
        container_name: ${COMPOSE_PROJECT_NAME}-postgresdb
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./.cache/postgresdb/:/var/lib/postgresql/
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 3s
            timeout: 1s
            retries: 5
        user: ${UID}:${GID}
